service: hemi-routing-api

useDotenv: true

custom:
  esbuild:
    packagePath: '../package.json'
    watch:
      pattern: ['./api/**/*.ts', '../lib/**/*.ts']
  serverless-offline:
    httpPort: 4000

functions:
  get-quote:
    events:
      - http: 
          method: post
          path: /v2/quote
          cors: true
    handler: ./index.post
    timeout: 30

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  environment:
    WEB3_RPC_743111: ${env:WEB3_RPC_743111, ''}
  name: aws
  region: ${opt:region,env:AWS_REGION,'eu-central-1'}
  runtime: nodejs20.x
  stage: ${opt:stage,env:STAGE,'dev'}
